### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Vorschreibung** [acqu/rtcw-wet-blender-model-tools#20]
Hi,

I'd like to package this for ArchLinux and am wondering what License `rtcw-wet-blender-model-tools` is published under.
There's some references to GPL2.0 - but it would be nice if you could confirm.

Adding a LICENSE file to the repository root would also help, e.g.: https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

Thanks for a response and great work here!

**Comment by mino-git** [comment]
Hi, can you tell me what you mean by "package this for ArchLinux"? Is it packaged officially into ArchLinux then? Would be great!

Either way, the license is GPL 2+, as you can see from the source code files (just open one, it is on the header of every single file on the source code).

Before you package, keep in mind there is an .mdc fix pending, which i need to push in the next couple of days / weeks. So you might want to wait a bit, i will inform you if the push is done if you want. If you want to package now, take the latest download here on github, because the download on the documentation still points to an older version where an mds issue is still not fixed.

**Comment by mino-git** [comment]
Added the license.
